3

diff --git a/.github/workflows/dev-cicd-aws.yaml b/.github/workflows/dev-cicd-aws.yaml
--- a/.github/workflows/dev-cicd-aws.yaml
+++ b/.github/workflows/dev-cicd-aws.yaml
@@ -1,12 +1,12 @@
-name: istory ci/cd pipeline
+ name: istory ci/cd pipeline
 
 on:
   push:
-    branches: [ "develop"]
+    branches: [ "develop","main" ]
   pull_request:
-    branches: [ "develop"]
+    branches: [ "develop","main" ]
 jobs:
-  verify_pipeline:
+  verify-pipeline:
     environment: runner
     runs-on: ubuntu-latest
     services:
@@ -39,3 +39,19 @@ jobs:
         distribution: 'temurin'
     - name: Run test java
       run: ./gradlew test
+
+    - name: Notify on Failure
+      if: failure()
+      run: |
+        echo "Tests failed! Pipeline will be stopped."
+        exit 1
+
+    - name: Upload Test Report
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-report
+        path: |                    # 여러 경로 지정
+          **/build/reports/tests/test/
+          **/build/test-results/test/
+        retention-days: 30 
